---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: control-plane-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-plane-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - patch
  - update
  - create
- apiGroups: ["extensions", "apps"]
  resources:
  - deployments
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-plane-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-plane-operator
subjects:
  - kind: ServiceAccount
    name: control-plane-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane-operator
  template:
    metadata:
      labels:
        app: control-plane-operator
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      containers:
      - image: registry.svc.ci.openshift.org/hypershift-toolkit/hypershift-4.4:control-plane-operator
        imagePullPolicy: IfNotPresent
        name: control-plane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - --initial-ca=/etc/kubernetes/config/initial-ca.crt
        - --target-kubeconfg=/etc/kubernetes/kubeconfig/kubeconfig
        - --namespace=${POD_NAMESPACE}{{ range $controller := .ControlPlaneOperatorControllers }}
        - --controllers={{$controller}}{{ end}}
{{ if .ControlPlaneOperatorResources }}
        resources:{{ range .ControlPlaneOperatorResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{ end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
        - mountPath: /etc/kubernetes/config
          name: config
      restartPolicy: Always
      serviceAccountName: control-plane-operator
      volumes:
      - name: kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
      - name: config
        configMap:
          name: control-plane-operator
